Create new method getShipmentsByOrder
shoppingflux/php-sdk pull request #113
Opened 2023-12-05 09:17 UTC by hbouffi

### Link to the issue
Link here the issue this PR resolve if reletad to an issue.

### Reason for this PR
Explain in short words what need this PR resolve.

### What does the PR do
Explain in short words what feature is added or how is a bug fixed

### How to test
Give a quick explanation on how to test the modification

2023-12-12 09:29 UTC, Aurelieluciani commented on src/Api/Order/Shipment/ShipmentItem.php
> +    private $quantity;
Tu peux directement typer sur la ligne.

2023-12-12 09:30 UTC, Aurelieluciani commented on src/Api/Order/ShipmentResource.php
> +namespace ShoppingFeed\Sdk\Api\Order;
```suggestion

namespace ShoppingFeed\Sdk\Api\Order;
```

2023-12-12 09:31 UTC, Aurelieluciani commented on src/Api/Order/ShipmentResource.php
> +    public function getCreatedAt(): ?\DateTimeImmutable
Le createdAt peut être null ?

2023-12-12 10:09 UTC, Aurelieluciani commented on tests/unit/Api/Order/ShipmentResourceTest.php
> +        $this->assertEquals(date_create_immutable($this->props['createdAt']), $instance->getCreatedAt());
Plutôt utiliser DateTimeUmmutable ici.
Le setUp est il vraiment utile ? Tu peux directement passer les $props dans initHalResourceProperties.

Même si ce ne sont que des tests, n'hésites pas à cleaner le code (typage, alignement dans le tableau, espace avant [, etc)

2023-12-14 11:27 UTC, mdumoulin commented on src/Api/Order/OrderDomain.php
> +    }
Je pense que pour mieux respecter le design du SDK, tu devrais créer un objet ShipmentDomain. Ça devrait donner quelque chose comme ça in fine : 

```php
public function getShipmentsByOrder(int $orderId): array
{
    return (new ShipmentDomain($this->link->withAddedHref($orderId . '/shipment')))->getAll();
}
```

À voir l'usage, mais ce serait probablement plus pertinent d'ajouter une méthode dans la Ressource Order plutôt que dans le Domain Order : 

```php
public function getShipments()
{
    return (new ShipmentDomain($this->link->withAddedHref($this->getId() . '/shipment')))->getAll();
}
```

Ça permettra d'écrire ce genre de chose : 

```php
foreach($orderApi->getAll($criteria['filters']) as $order) {
    foreach ($order->getShipments() as $shipment) {
        echo $shipment->getTrackingNumber()
    }
}
```

2023-12-14 11:29 UTC, mdumoulin requested changes
J'ai laissé un commentaire. Il faudra également mettre la doc à jour dans docs/manual/resources/order.md

2023-12-20 09:30 UTC, mdumoulin requested changes
Merci @hbouffi. Je t'ai fait 2 petits retours. Disponible pour en discuter si besoin.

2023-12-20 09:30 UTC, mdumoulin commented on src/Resource/AbstractResource.php
> +    }
Ça n'est pas utilisé et peut-être supprimé.

2023-12-20 09:30 UTC, mdumoulin commented on src/Api/Order/Shipment/ShipmentDomain.php
> +    }
Tu ne devrais pas avoir besoin de surcharger la méthode getAll(). Il faut fournir la propriété $resourceClass avec la bonne classe Resource.

2024-01-02 10:30 UTC, mdumoulin approved these changes
Ok pour moi. Merci @hbouffi

2024-01-02 10:37 UTC, merged