SFCNT-33 Add catalog domain and operation
shoppingflux/php-sdk pull request #95
Opened 2020-12-29 17:03 UTC by budrea

### Link to the issue
https://shopping-feed.atlassian.net/browse/SFCNT-33

### Reason for this PR
After having added the link to the catalog domain in [this PR](https://github.com/shoppingflux/api/pull/793), we add the catalog domain & resource here, which allow us to : 
- [get the catalog](https://next.stoplight.io/shopping-feed-1/api/version%2F1.1/catalog.oas2.yml?view=%2Fcatalog%2Fv1catalogget)
- [ask for an operation](https://next.stoplight.io/shopping-feed-1/api/version%2F1.1/catalog.oas2.yml?view=%2Foperation%2Fv1catalog-operationpost)

I'm aware that : 
- these 2 end-points are currently unpublished
- the operation end-point concerns 2 possible operations, one of which is only available for certain roles

But : 
- I'm guessing the catalog end-point will soon be published (and as long as it is not officially published, people, if they use it, will use it at their own risk)
- for the operation end-point, I've opted for the simplest solution (integrate it in the public SDK and let the API decide if the user is allowed or not to carry out the operation, based on his/her role)

### What does the PR do
This PR allows asking for an import using the SDK. This is necessary, so as to refactor the legacy project.

### How to test

If [this PR](https://github.com/shoppingflux/api/pull/793) is not yet merged, please make sure you are on the branch associated with this PR (on the API project) before testing. 

To test, you can use the following script

```php
<?php
include 'vendor/autoload.php';

date_default_timezone_set('Europe/Paris');

$userToken = 'TOKEN'; // replace with a real token

$credential    = new \ShoppingFeed\Sdk\Credential\Token($userToken);
$clientOptions = new \ShoppingFeed\Sdk\Client\ClientOptions();
$clientOptions->setBaseUri('http://api.shopping-feed.lan');

$session = \ShoppingFeed\Sdk\Client\Client::createSession($credential, $clientOptions);
$store   = $session->getMainStore();

$catalogDomain = $store->getCatalogApi();
$catalogDomain->askForFeedImport();
```
and launch it in the command line : 
`php test.php`
(assuming you named the file `test.php`; please launch the command outside the Docker container)

If everything works OK, you should see a new published message on RabbitMQ (local) >> Queues >> `sf.catalog.feed:dispatch`.

2021-01-04 09:14 UTC, ddattee commented on src/Api/Catalog/CatalogDomain.php
> +    public function askForFeedImport($force = null)
Si tu peux ajouter les type hint de retour en docblock. On ne type pas pour rester compatible php5.6 mais c'est quand même bien de figer/documenter le typage.

2021-01-04 09:16 UTC, ddattee commented on src/Api/Catalog/CatalogDomain.php
> +    public function askForFeedImport($force = null)
```suggestion
    public function requestFeedImport($force = null)
```
Serait plus clair. et il faut documenter le $force pour savoir a quoi il sert (dans le code et dans la doc du repo)

2021-01-04 09:17 UTC, ddattee commented on src/Api/Catalog/CatalogDomain.php
> +    public function askForFeedImport($force = null)
Pas sur que le retour sur cette méthode soit vraiment utile, si c'est un process asynchrone qui est demandé.

2021-01-04 09:19 UTC, budrea commented on src/Api/Catalog/CatalogDomain.php
> +    public function askForFeedImport($force = null)
ça peut être utile, si jamais on veut avoir la réponse : un 202, si tout se passe bien.

2021-01-04 09:25 UTC, ddattee commented on src/Api/Catalog/CatalogDomain.php
> +    public function askForFeedImport($force = null)
Il me semble que le comportement de base pour les call asynchrone d'opération (ex: [les opérations orders](https://github.com/shoppingflux/php-sdk/blob/master/src/Api/Order/OrderOperation.php)) :
- si tout est ok > on retourne rien
- sinon > Exception

2021-01-06 09:02 UTC, ronan-gloo requested changes
L'implementation ne reflète pas le design général du SDK, notamment l'accès implicite aux resources (CatalogResource) et le model (un import est associé à une resource et la méthode doit être définie à ce niveau).

Il faut essayer de s'inspirer des autres composants, et si ce n'est pas clair on s'attèle à une documentation.

2021-01-06 09:51 UTC, ronan-gloo commented
Je ferme la PR pour passer l'implémentation en private

2021-01-06 09:51 UTC, closed without merging